[project]
name = "hybrid-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "datasets>=5.0.1",
    "deepeval>=4.1.8",
    "dotenv>=0.9.9",
    "fastembed>=0.8.0",
    "langchain-core>=1.5.6",
    "langchain-huggingface>=1.2.2",
    "langchain-ollama>=1.1.0",
    "langchain-qdrant>=1.1.0",
    "langchain-text-splitters>=1.1.2",
    "qdrant-client>=1.19.0",
    "sentence-transformers>=5.7.0",
    "torch>=2.13.0",
    "transformers>=5.15.0",
]
